### ISSUE TITLE
Dropdown not showing

### ISSUE THREAD

**Issue by ImVexed** [fdefelici/react-bootstrap-combobox#72]
When using a combobox inside a react-boostrap Form, (or maybe other places aswell) `dropdown-menu` has `display: none;` which overrides the `open` className set when the combobox is clicked. And due to `open` not having `display: block` set to important, no menu is shown.

This also seems to effect the actual `ul` as `dropdown-menu`'s `display: none` is also applied to it causing nothing to show even if the the `open` issue is fixed.

In total I was able to fix by:
setting `open` to `display: block !important`
as well as `inner` to `display: block`

On Chromium
react-bootstrap-combobox: 1.4.0
bootstrap: 4.3.1
react-bootstrap: 1.0.0-beta.14

**Comment by fdefelici** [comment]
Hi @ImVexed thanks for reporting to us.

The issue is due to the bootstrap version you are using that is 4.3.1, while this widget is compliant with bootstrap >= 3.3.0 and < 4.0.0 as reported in documentation [README](https://github.com/fdefelici/react-bootstrap-combobox/blob/master/README.md) and "Usage" paragraph.

We have in our roadmap the a version of this widget specific for bootstrap 4+ (probably before the end of the year).
